### ISSUE TITLE
Create new get_all_content function

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#109]
Must product more performant SQL than the current version.

Perhaps using code like the following:

https://www.quora.com/How-do-I-override-a-max-limit-of-61-joins-in-a-MySQL-query

Provide better pagination interface. 

Provide better 'included fields' interface, and maybe a better 'hide fields' interface.

Provide better 'search' interface - though searches may have to be done manually, or maybe fields in custom fields json files should have a 'searchable' property. (False by default or if omitted). Perhaps even a 'searchable_method' indicating partial (like) or full string matching.

**Comment by bobmitch** [comment]
Must also handle filters passed for columns. Started on staff.holtbosse.com - something like this:

![image](https://user-images.githubusercontent.com/23583515/166126948-e040485a-6ca7-4d37-84f3-1bae93670f9d.png)

![image](https://user-images.githubusercontent.com/23583515/166126956-33ee572c-f56b-4a7f-b779-ffbb13ff38e1.png)

**Comment by bobmitch** [comment]
Started in https://github.com/bobmitch/SeamlessCMS/commit/dc2ab4f9248c29818c72bd0d1c3eeaf8752c8ef6

**Comment by workaj** [comment]
@bobmitch possible close?

**Comment by bobmitch** [comment]
@workaj good call
