### ISSUE TITLE
Add ability to insert metatag data at any point pre-output

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#11]
Add metatag array to CMS for rendering after widgets/controller/plugins have executed.
Add CMS function 'set_metatag'. Params: $name, $content, $attribute = 'name' (default).

e.g. setting an opengraph metatag could be achieved by running:

`CMS::Instance()->set_metatag('og:title','title text','property');`

Then pre-render, replace head placeholder (maybe something like  {HEAD} in template) with call to CMS render head which goes through metatag array and outputs.

**Comment by bobmitch** [comment]
now replaced in template after all controllers have run - add set_metatags function using above structure to render_head function in cms.php

**Comment by workaj** [comment]
instead of just meta tags, why not just put a hook in the head that anything can call, for adding custom tags, css, js, etc?

**Comment by bobmitch** [comment]
Has crossed my mind before. Maybe just have an array of strings that get spat out during the CMSHEAD replacement.
To add something, maybe an interface like:

```php
CMS::Instance()->head_entries[] = "<style>h1 {display:none;}</style>";
```

or something?

**Comment by workaj** [comment]
completed in https://github.com/HoltBosse/Alba/commit/e1ab2b57ecc3422d5e19176dd0777d0a42b51279
