### ISSUE TITLE
Image fig-caption wysiwyg needs to honor image float status.

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#137]
Class for pull needs to be applied to new parent figure as well.
**One day** this will be handled by the :has selector - but this probably won't be till 2023.

**Comment by bobmitch** [comment]
@anthonyisensee fyi - we can chat tomorrow if this doesn't make sense

**Comment by anthonyisensee** [comment]
@bobmitch can we just wait until 2023 to fix this issue? ;) Jk, see my dm.
