### ISSUE TITLE
make form fields ids repeatable

### ISSUE THREAD

**Issue by workaj** [HoltBosse/Alba#146]
with https://github.com/HoltBosse/Alba/pull/145 added, we need a way of changing id to be repeatable friendly

**Comment by bobmitch** [comment]
the existing way works for newly added repeatable items but is... somewhat entirely borked for items loaded from saved repeatable. it's solveable, but will need time tomorrow as I'm done thinking about it today. 

basically I need to only inject the '{{id_suffix}}' nonsense when creating the template form markup to be injected every time the repeatable + is clicked.  OR come up with a better way of doing them.
