### ISSUE TITLE
Hybrid EAV + Relational Custom Content

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#155]
Investigate possibility of further increasing the flexibility of the existing relational (content) / [eav](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) (content_fields) model with per-content-type tertiary tables that are relational in nature on a per-field basis for performance reasons.

Should allow custom forms fields to dictate if they should be stored in a per-content-type tertiary table allowing more performant searching/querying with only two relational tables, using the eav for single entity retrieval.

Explore:

- Auto schema / column generation based on form json.
- Auto migration from eav (content_fields) table and vice-versa.
- Handle magically in [content_search](https://github.com/HoltBosse/Alba/blob/master/core/content_search.php) class.

**Comment by workaj** [comment]
"fixed" by flat
