### ISSUE TITLE
Backup does not capture my_404.php at root if it exists

### ISSUE THREAD

**Issue by anthonyisensee** [HoltBosse/Alba#175]
@bobmitch in checking for 404 on new site discovered this. Is it something we'd hypothetically like the backup to do?

**Comment by workaj** [comment]
not bob, but yes. added in https://github.com/HoltBosse/Alba/commit/9a19a9637752b253b1ec296185a59cf23cb28eef

**Comment by bobmitch** [comment]
actually fixed here: https://github.com/HoltBosse/Alba/commit/208e112f647f18cfd93f814c6894cf9753deedb6

**Comment by workaj** [comment]
not actually fixed

**Comment by bobmitch** [comment]
actually for reals fixed here: https://github.com/HoltBosse/Alba/commit/acfde6b4057c5c90bc16a711c6e0789378ade5c7
