### ISSUE TITLE
Version save count is not preserved... or something.

### ISSUE THREAD

**Issue by anthonyisensee** [HoltBosse/Alba#176]
After changing the "Version Save Count" to 0 and saving a 3 is displayed.

![image](https://user-images.githubusercontent.com/60198052/186427324-4f8176df-6f86-45cc-a00c-8c27c6d3682c.png)

**Comment by bobmitch** [comment]
I need to remove versioning from main/stable branch then continue working on its own branch until it's cooked a little longer.

**Comment by bobmitch** [comment]
Fixed in https://github.com/HoltBosse/Alba/commit/74d2d15475ed2f56f720b69a3b48e9ac09dff66e
Versioning was already ignored in main branch, and nothing to do with this bug.
