### ISSUE TITLE
Recaptcha javascript is included everywhere

### ISSUE THREAD

**Issue by anthonyisensee** [HoltBosse/Alba#179]
Happens regardless of whether or not there is a form with recaptcha on the page. Google lighthouse does not like:

![image](https://user-images.githubusercontent.com/60198052/186501821-63dd91ef-a99b-450b-ba9b-c40701569494.png)

**Comment by bobmitch** [comment]
Excellent find. This will happen in the next day or two.

**Comment by bobmitch** [comment]
https://github.com/HoltBosse/Alba/compare/fasterrecaptcha?expand=1

**Comment by workaj** [comment]
fixed in https://github.com/HoltBosse/Alba/commit/c94ceadad629c6393f5b1ba6fc4f7a0a1f90442c
