### ISSUE TITLE
Custom fields for Tags and Categories

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#208]
Use case: Icon images for tags on visit escanaba - currently existing image field is used for header. Be nice to have icons managed there. Make it happen.

**Comment by bobmitch** [comment]
@HBJosh - fyi @workaj requested something similar to your tag icon thing for categories, so going to build out the ability to customize the fields for both on a per-site basis, just in case we want even _more_ fields later.

**Comment by HBJosh** [comment]
Thank you.

**Comment by bobmitch** [comment]
https://github.com/HoltBosse/Alba/commit/b2e44fbe085a5c08f150d714cc4975068fa2a6e5
