### ISSUE TITLE
Custom filtering per-content type in admin

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#222]
Per recent request from BN client - they would like to be able to filter events based on date range.

This presents a challenge for the Content_Search class - as filtering is done on a value basis. We'd need to come up with a robust solution for ad-hoc queries - and not only based on content table fields, but arbitrary fields.

It is planned that repeat events will be stored in a tertiary table for fast lookups - and this table will be updated via the content save plugin that currently generates a json cache instead. 

So we probably need a way to pass arbitrary SQL along with a safe way of parameterizing the variables (and make it work with the existing content search class)

A plugin to inject a filter form into the admin filter interface - along with another function/hook to use these submitted values within the content search class itself. Several new hooks would be required in the core for this to work.

This could be quite flexible for creating complex filters in the content admin area.

**Comment by bobmitch** [comment]
Plugin for testing right now looks a little bit like this:

```php
<?php
defined('CMSPATH') or die; // prevent unauthorized access

class Plugin_custom_content_search_controls extends Plugin {
    public function init() {
        CMS::add_action("render_custom_content_search_filters", $this, 'render_controls'); 
        CMS::add_action("custom_content_search_from",$this,'update_from'); 
        CMS::add_action("custom_content_search_where",$this,'update_where'); 
        CMS::add_action("custom_content_search_select",$this,'update_select'); 
    }

    public function render_controls($args) {
        // ACTION
        ?>
        <div class="field">
			<label class="label">Test Filter</label>
			<div class="control">
				<input value="" name="test_filter" form="searchform" class="input" type="text" placeholder="">
			</div>
		</div>
        <?php
    }

    public function update_select ($select, ...$args) {
        // FILTER
        return $select;
    }

    public function update_from ($from, ...$args) {
        // FILTER
        return $from;
    }

    public function update_where ($where, ...$args) {
        // FILTER
        return $where;
    }
}
```

**Comment by bobmitch** [comment]
Need to add a good way to also pass additional parameterization to the main search query. 

The content search class already uses

```php
$this->filter_pdo_params
```

For built-in filtering. Might have to pass that variable to another update_ hook function in the plugin to add variable to this array. Problem for tomorrow. ;)

**Comment by bobmitch** [comment]
Content type aware custom searches possible via https://github.com/HoltBosse/Alba/commit/e516ef60ab0dbe3a5aabdd945dc97d08df8c4d60

**Comment by workaj** [comment]
https://github.com/HoltBosse/Alba/pull/224 implemented
