### ISSUE TITLE
Flat Content Conversion

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#295]
Convert system to use per-content item tables with configuration via json.

**Comment by bobmitch** [comment]
- [ ] Table conversion
- [ ] Field conversion
- [ ] Content search
- [ ] Content functions [ get_all_content_by_id most important ]
- [ ] Saving
- [ ] Versioning

**Comment by workaj** [comment]
@bobmitch seems you could probably check these all off and close this now?
