### ISSUE TITLE
Replace all instances of fetchAll PDO call with static DB::fetchall function call

### ISSUE THREAD

**Issue by bobmitch** [HoltBosse/Alba#31]
Has exception handling and error reporting/debug handling in place

i.e.

Replace

```
$query = "select * from widget_types";
$stmt = CMS::Instance()->pdo->prepare($query);
$stmt->execute(array());
$all_widget_types = $stmt->fetchAll();
```

With

`$all_widget_types = DB::fetchall("select * from widget_types");`

**Comment by workaj** [comment]
fixed https://github.com/HoltBosse/Alba/commit/b0675e167f27e2276e49795c1330a10a4f6fea85
